# site properties and page defaults
title: Health and Happiness Design Lab
subtitle: HCI@Stevens | Human-computer interaction, social computing, health informatics
description: We study people, understand people's needs, and foster social connectedness to improve health through emerging technology.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: jhuhyoo@stevens.edu
  orcid: 0000-0001-5811-9256
  google-scholar: e4mFUawAAAAJ
  github: https://huhjina.github.io/personal/
  twitter: @dr_jinahuhyoo
  youtube: huhjina

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
